### ISSUE TITLE
Help with error: Uncaught X: Cannot inject value into "Object.entityModule". Please make sure you setup reflect-metadata properly and you don't use interfaces without service tokens as injection value.

### ISSUE THREAD

**Issue by CollinEstes** [sascha245/vuex-simple#14]
-  **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[X] question about how to use this project

-  **Summary**
I'm working in a typescript Vue-cli3 project where we are also using vuex-simple.  When running `vue-cli-service serve` (webpack-dev-server) my application is working as expect with vuex-simple.  However when running `vue-cli-service build` and then serving those static assets with an NGINX server I am getting the following

```
inject-util.js:48 Uncaught X: Cannot inject value into "Object.entityModule". Please make sure you setup reflect-metadata properly and you don't use interfaces without service tokens as injection value.
    at i.forEach.n (http://localhost:4000/js/chunk-vendors.3e2289df.js:1317:10455)
    at Array.forEach (<anonymous>)
```

I'm not sure what the difference in what I'm doing with NGINX vs what the webpack-dev-server is doing, but I'm wondering if you could help point me to what configuration I have incorrect in my build process that I'm getting this error out of vuex-simple?

I do have 
```
import 'reflect-metadata';
```
in my main.ts (entrypoint)

**Comment by sascha245** [comment]
Good morning @CollinEstes,

I made some tests in a new project with a simple counter module and couldn't find any problems when building and serving it with `serve -s dist`.

As I couldn't reproduce the error on my part I am not sure this will work, but you can test out removing
the following 3 lines for now in *node_modules/vuex-simple/build/src/utils/inject-utils.js* between lines 56-58:
```ts
if (identifier === Object) {
  throw new CannotInjectError(_this, propertyName);
}
```

If that solves the problem, tell me and I will commit a fix for this issue if it doesn't break anything else.

If it doesn't, then I would like to ask for more informations, like if it happens on a specific browser, or if you have an example that I can use to reproduce the error.

Sascha

**Comment by CollinEstes** [comment]
@sascha245 thanks, I'll try that here today and see.  Interestingly my application works fine when building with `--mode development`, so it is just something with the way my `production` mode build is working.  Still investigating...

**Comment by sascha245** [comment]
So, your pull request has been merged and published on npm.
I will let you close the issue if everything is fixed in 1.2.2.

I wish you a good evening

**Comment by CollinEstes** [comment]
thanks @sascha245, looks good.

**Comment by andi2233i** [comment]
我有相同的问题，当我用esbuild 编译 typedi @service construct时

**Comment by andi2233i** [comment]
I had the same problem when I compiled typedi@service construct with esbuild
