### ISSUE TITLE
Major update 2.0.0

### ISSUE THREAD

**Issue by sascha245** [sascha245/vuex-simple#17]
Hi everyone,

Being not very familiar with github and not knowing where else to put it, I will post my announce here.

I will probably make a new major version soon (in the next 1-2 weeks) to cleanup unnessecary and deprecated features, as it becomes more and more difficult to add new useful features without first removing the older parts from the codebase.

That is why I will first ask once if the changes seem meaningful (or not) or if there are important features I am missing.

Here the planned changes:

- Remove typedi / dependency injection by default, as it is not the main concern of this library. 
That way, you will also be able to choose the DI library you want to use (if you want to use one).

- The modules stay the same, with just the `@Module` decorator changing its role: It is now used to declare submodules. We don't need to attach the decorator to the class anymore.
```ts
class FooModule {

	@State()
	public counter = 0;

	constructor(nb: number) {
		this.counter = nb;
	}

	@Mutation()
	public setCounter(counter: number) {
		this.counter = counter;
	}

	// use as previously
	...
}

class BarModule {

      	// property name becomes module namespace
	@Module()
	public foo1 = new FooModule(5);
	
	@Module()
	public foo2 = new FooModule(7);

	@Getter()
	public get totalCount() {
		return this.fooModule1.counter + this.foo2.counter;
	}

	// use as previously
        ...
}
```

- The store will in the end also be build from a module, this also allows us to type the root of our store.
As we don't use a DI library anymore, we can also easily create multiple stores without having to worry about having multiple instances of a same module.
```ts
class MyStore {
	
	@Module()
	public bar1 = new BarModule();
	
	@Module()
	public bar2 = new BarModule();

	@State()
	public version = "1.0.0";
}

const store = createVuexStore(new MyStore(), {
	strict: false,
	modules: {},
	plugins: []
});
```

- The usage doesn't change a lot either, but instead of using a container and injecting our modules, we simply use  `@Store` to access our typed root module that will be somewhere within `this.$store`.

```ts
class MyComponent extends Vue {
	
	// get the root module of the store	
	@Store()
	public store!: MyStore;

	// get module by its namespace
	// Note: it is better to store namespaces in an enum or somewhere else to refactor with more ease
	@Store("bar1/foo1")
	public foo1Module!: FooModule;

	// get modules from the root module instance
	public get bar1foo2() {
		return this.store.bar1.foo2; // everything is typed naturally
	}

	// simply use as previously
}
```

Once again, don't hesitate to tell me what you think about these changes and if they seem meaningful or not.

I wish you a good evening,

Sascha

**Comment by shmaram** [comment]
Hi @sascha245 

Thank you for listening to our thoughts, I'm so exited to hear about the coming changes! 
Here are some inputs:

1. In the module declaration it feels like there are 2 ways to have initial value. 
     * one by assigning a value to the state 
        @State()
	public counter = 0;
     * via the constructor.
It feels to me that only one way should be kept in order to avoid confusion. 
I would go with the second option

2. regarding the @Module decorator change. I was thinking if it might be possible to keep the declaration as it was and perhaps use another declaration such as @SubModule or to add a bool flag to the existing module decorator such as
@Module({name:'foo', isSub: true}). of course it can also have a default value
That way it will be less breaking changes and also we define the name of the module once and not in each time we inject it to the class the uses it 
       @Store("bar1/foo1")
	public foo1Module!: FooModule;

I would love to hear your thoughts 
Shahar

**Comment by sascha245** [comment]
Hi @shmaram,

Thanks for your inputs!
My bad for not elaborating enough on why I planned to do it the way described above.
Here some of my thoughts:

**1. Initialization**

- In fact, JS / TS classes allows us to initialize our values either inline or via the constructor. As I am trying to make modules approach the most possible normal classes, in a way it seemed logical to me to give the user the choice between using one or the other

- Inline initialization is nice when we have no complex values and simply want to initialize our variable at a fixed value.

- Initialization via constructor is useful in more advanced usecases:
  - When we need multiple module instances of the same class but with different initial values
  - As there won't be any injections by default in *vuex-simple* anymore, in the case where *module B* needs a *module A*, we can simply pass *module A* to *module B* via the constructor when instantiating it:
```ts
class MyStore {
  @Module()
  public moduleA = new ModuleA();

  @Module()
  public moduleB = new ModuleB(this.moduleA);
}
```

In the end, when `createVuexStore(new MyStore())` is called and the root module and all submodules are transformed, all the initialization will already be done. 
In a way, you could simply instantiate `MyStore` and use it as a normal class, as all special decorators (State, Getter, Mutation...) are never applied until you pass your module to `createVuexStore`.

**2. Modules and submodules**

Concerning modules, at the start I was also playing with the idea to keep `@Module` and make a `@Submodule` decorator, but after thinking about it for some time, I found out a  few things:

- When we need to instantiate a module class twice or more (see example above), we can't use the same namespace for both. So it is better to use a always use the name from `@Submodule` as the namespace.
In that case, we simply don't need `@Module` anymore, as we don't gain anything from keeping it. On the contrary, it might lead to confusion, as we don't know which name will be used.

- Giving the possibility to change the name/namespace of the module via parameters in `@Submodule` won't lead to any good outcomes. In the worst case, there may even be conflicts between a `@State` and `@Submodule` if they have the same name, as both are placed in the state once the store has been created:
```ts
class MyModule {
  // in the store: state.foo
  @Submodule('foo')
  public fooModule = new FooModule();
  
  // in the store: state.foo
  @State()
  public foo = 10;
}
```
That is why I planned to directly use the **property name** as the module namespace. That way the compiler / linter can directly tell us that something might go wrong. 

- As the `@Module` decorator is removed, the `@Submodule` can also be renamed to `@Module`, but this change doesn't have any important reasons and is more to reuse the `@Module` decorator that is going to disappear.

**3. Usage**

Concerning module injections in our vue components, as we can now have multiple instances of the same modules in our store, we can only find the correct module by looking it up with the namespace :s

However, you can for example use an enum to store your namespace strings:
```ts
enum MyStoreNamespaces {
  BAR1 = "bar1";
  BAR1_FOO1 = "bar1/foo1";
  BAR1_FOO2 = "bar1/foo2";
  BAR2 = "bar2";
  BAR2_FOO1 = "bar2/foo1";
  BAR2_FOO2 = "bar2/foo2";
}
```
That way you can easily refactor and track errors on compile time, though this solution isn't perfect.

If you don't want to use this method, you can also simply inject the root module with `@Store()` and access the module you are looking for from that root module, which is actually the safest and best solution.


Hope that explains some of my ideas a bit more for you.

Sascha

**Comment by shmaram** [comment]
Hi @sascha245 

Thank you for the comments, they were very helpful. 
Waiting for the release.

Shahar

**Comment by sascha245** [comment]
So, major version 2.0.0 has been published.
The README should explain most of the changes, but here a a small recap and a few reasons why you might want to migrate to the new version:

**Why**
- You don't need dependency injections / You want to use a custom dependency injection library.
- You need submodules
- You want to have multiple stores / modules instances.

**Breaking changes:**

- Dependency injection support has been removed from this module and put in a separate one: [vue-typedi](https://github.com/sascha245/vue-typedi).
Examples are available in the README and in the samples folder.

- You don't need `@Module` decorator anymore on top of your module class. This decorator will now be used to declare your submodules.

- The store creation has drastically changed: You simply pass your module class instance to the `createVuexStore` function. During this call, the instance is transformed to use the state, getters, mutations, etc... from the store.
Examples are also available in the README and in the samples folder.

- You can use `useStore(this.$store)` to get the module instance you passed to `createVuexStore`.

Hope that will make the migration a bit easier,

Sascha
