### ISSUE TITLE
Error when using Vue component with module injection

### ISSUE THREAD

**Issue by shmaram** [sascha245/vuex-simple#20]
-  **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

Hi @sascha245 

Please see that in the docs you have 
```
Container.set(instance.bar, tokens.BAR);
Container.set(instance.bar.foo1, tokens.BAR_FOO1);
Container.set(instance.bar.foo2, tokens.BAR_FOO2);
```
and in the example code it is 
```
Container.set(tokens.MY, instance.my);
Container.set(tokens.TEST, instance.test);
Container.set(tokens.TEST_MY1, instance.test.my1);
Container.set(tokens.TEST_MY2, instance.test.my2);
```

I belive that the docs are wrong

**Comment by sascha245** [comment]
Hi @shmaram,

Yep I made a small mistake in the docs, my bad.
The README has now been fixed. I also added some more content with more details about how to do / use some things with this library.

Sascha
