### ISSUE TITLE
Method style access getters

### ISSUE THREAD

**Issue by ReinisV** [sascha245/vuex-simple#22]
-  **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

-  **Summary**
How does one define a [method style getter](https://vuex.vuejs.org/guide/getters.html#method-style-access)?
*  **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I tried doing a simple

```
    @Getter()
    public getNumberButIncreased(someNumber) {
        return someNumber + 1;
    }
```

but that gives me the following error:
`{code: "getter_not_found", message: "Could not find getter "getNumberButIncreased" for module SomeModule", params: {…}} code: "getter_not_found" message: "Could not find getter "getNumberButIncreased" for module SomeModule" params: className: "SomeModule" propertyName: "getNumberButIncreased" } }`

[As far as I can see](https://github.com/sascha245/vuex-simple/blob/b0121efe03228523ed912519305f3f34351c49d3/src/store.ts#L128), the code always assumes that a @Getter will actually always be a getter field and never a function.

**Comment by sascha245** [comment]
Hi @ReinisV,

Yes that is right, the `@Getter` decorator only works on a getter field. In that way, it is the same as vuex getters, as they too can't really take arguments.

You can however pass arguments to getters by returning a function, like how it is described on the official documentations of vuex:
https://vuex.vuejs.org/guide/getters.html#method-style-access

```ts
// Getter
@Getter()
public get numberButIncreased() {
    return (someNumber: string) => {
        return someNumber + 1;
    }
}

// Usage
myModule.numberButIncreased(5); // returns 6
```

**Comment by ReinisV** [comment]
Oh, okay, that makes sense :) thanks for the help. 

Would this be something that could be included in the samples, so that others can avoid this misunderstanding?

**Comment by sascha245** [comment]
No problem and yes sure ;-)
I will add some samples and a section in the README concerning [method style getters](https://vuex.vuejs.org/guide/getters.html#method-style-access) in the next few days.

**Comment by sascha245** [comment]
I have added an example in the readme under the getters section, as well as in the store module in the samples. That should help people who need this feature in the future.
