### ISSUE TITLE
Access to local state and rootState within modules

### ISSUE THREAD

**Issue by royprigat** [sascha245/vuex-simple#24]
-  **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

-  **Summary**
By default, Vuex offers access to a local state within modules. Is there a way to access the local state within modules in vuex-simple as well? For example inside an action function you can get access to state or rootState, as can be seen in the Vuex docs...

-  **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Link to Vuex docs: https://vuex.vuejs.org/guide/modules.html

**Comment by sascha245** [comment]
Hi @royprigat,

You can access all properties (including your state) of your class anywhere inside your classes functions (including mutations, actions and normal functions) with `this`. Nothing changes in the way you would normally use classes.

Concerning the rootState, it isn't directly accessible to the submodules. You can however pass your root module instance to your child module if required:
```ts
// pass module instance to submodule
class MyStore {
  ...
  @Module()
  public submodule = new MyModule(this);
  ...
}

// use module instance
class MyModule {
  private myStore: MyStore;

  constructor(myStore: MyStore) {
    // put myStore in a property and use it later
    this.myStore = myStore;
  }
}
```
The same works if you need access to state, mutations or actions of module A in a module B: you can simply pass the instance of A in the constructor of B.

If you want I can also add some more samples to the repository concerning those points.

Hope that answers your questions,

Sascha

**Comment by royprigat** [comment]
Thanks for the quick response Sascha.
I understand your example above, but my concern is how to get the rootState in a regular module in the first place(not sub-modules).
Also, when I try to reference this.$route in a Module class for example, I get an error that $route is undefined...

**Comment by sascha245** [comment]
Mmh I think I don't understand your problem correctly.
The rootState you speak of doesn't exist in vuex-simple. You can however pass down the instance of your rootModule (which contains the rootState) to the module that needs it like shown above. 

Taking the examples from https://vuex.vuejs.org/guide/modules.html, you could rewrite those in the following way:
```ts
class ModuleA {
  @State()
  public count: number = 0;
  
  @Getter()
  public get doubleCount() {
    return this.count * 2;
  }

  @Getter()
  public get sumWithRootCount() {
    return this.count + this.root.count
  }

  constructor(private root: RootModule) {}

  @Mutation()
  increment() {
    this.count++;
  }

  @Action()
  incrementIfOddOnRootSum () {
    if ((this.count + this.root.count) % 2 === 1) {
      this.increment();
    }
  }
}

class RootModule {
  @State()
  public count: number = 0;

  @Module()
  public a = new ModuleA(this);
}

const store = createVuexStore(new RootModule());

store.state.a // -> `a`'s state
store.commit('a/increment') // works
store.dispatch('a/incrementIfOddOnRootSum') // works
```

Concerning `this.$route` returning undefined, this is quite normal, as a Vuex module isn't a Vue component. This wouldn't work in Vuex either (as far as I know). So if you want to use the current route, you need to pass it as a function parameter.

**Comment by royprigat** [comment]
Many thanks Sascha, this answers my questions

**Comment by sascha245** [comment]
No problem! Don't hesitate to ask if you have any other questions.

**Comment by sobolevn** [comment]
I guess this should also be mentioned in the `Module` doc section in the `README`.
I had the same question too and I had to google this issue 🙂 

I can contribute the documentation if that's ok.

**Comment by sascha245** [comment]
Hi @sobolevn 

You are very welcome to do so, I would even appreciate that :-)
