### ISSUE TITLE
registerModule from Action

### ISSUE THREAD

**Issue by SebastianS90** [sascha245/vuex-simple#27]
-  **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

-  **Summary**
I would like to program an Action that registers a dynamic module. Is there a way to get the `Store<any>` object that must be passed to `registerModule` from within the Action, e.g. something like `this.$store`?

*  **Other information**
I guess the way to implement it would be to let modules extend a base class that provides access to the vuex store (after being created by `createVuexStore`)

**Comment by sascha245** [comment]
Hi @SebastianS90,

Sorry for the wait, holidays are over now and I am fully available again.

For now, there isn't any variable like `this.$store` available. However, as actions aren't logged in the vuex devtools, you can also for now use a normal method that takes the store as a parameter to do what you want:
```ts
class MyModule {
    ...
    public myAction(payload: any, store: Store<any>) {
        // do something
        // register module
        registerModule(...)
        // call other actions or mutations
    }
    ...
}
```

Being able to access the store with something like `this.$store` inside of an action may be interesting to add, mostly for being able to dispatch/commit actions and mutations of non-class modules, so I will think about adding it.
