### ISSUE TITLE
Unit test practices

### ISSUE THREAD

**Issue by sobolevn** [sascha245/vuex-simple#29]
-  **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

-  **Summary**

What are the best practices to unit tests projects with `vuex-simple`?
I am taking about several topics:
1. Providing some state for the tests to run on; like here: https://github.com/wemake-services/wemake-vue-template/blob/master/template/tests/pages/index.spec.ts#L17
2. Mocking actions, getters, mutations; like here: https://github.com/wemake-services/wemake-vue-template/blob/master/template/tests/components/action-bar.spec.ts#L15
3. Creating test doubles for the actual `store` that is mounted with `mount()` from `vue-test-utils`; like here: https://github.com/wemake-services/wemake-vue-template/blob/master/template/tests/fixtures/vuex.ts#L34

Would be awesome to cover this things and to create a testing guide.

**Comment by sascha245** [comment]
Hi @sobolevn,

I don't have much experience in testing Vue components or such, but normally a lot of best practices from Vuex also apply for this library, as it is build on top of it.

Features such as `$store.replaceState` also work fine and can be used to set initial mock data.
For now, mocking actions / mutations and such is possible by doing it like in your examples with vuex, though there aren't any utils for mocking *vuex-simple* module classes yet.

In each case, it is true that for now testing is a bit unclear and needs to be clarified.
I will look into it in the next 1 or 2 weekends.

If you need some example right now, I could give you a few short ones using your examples as a base.

Have a nice day,

Sascha

**Comment by sobolevn** [comment]
Ok, I think that I will write a guide on this 🙂

**Comment by sobolevn** [comment]
I wrote a full test suite that other people might use as a example: https://github.com/wemake-services/wemake-vue-template/tree/master/template/tests
