### ISSUE TITLE
Adding vuex-simple sub module to existing native vuex store implementation

### ISSUE THREAD

**Issue by ziazon** [sascha245/vuex-simple#31]
-  **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ X] question about how to use this project

-  **Summary**
I'm trying to use this project to start building out new submodules for an existing app I have. But there doesn't seem to be any guide as to how to do this, and my attempts have thus far failed with errors like `'typeof SubModule' has no properties in common with type 'Module<any, any>'`

*  **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by scttcper** [comment]
Also interested. Would love to try this out in parts of the app, but there doesn't seem to be a clear way to mix vuex-simple and standard vuex

**Comment by sascha245** [comment]
If you want to use vuex-simple in addition to your existing vuex modules, the easiest way would be to use dynamic modules:

```ts
// First register your module and all of it's sub-modules
const my = new MyModule(6);
registerModule($store, ['namespace'], my);

// Use module in your component:
const myModule = useModule($store, ['namespace'])

// Or simply dispatch or commit any actions or mutations directly with vuex
$store.dispatch('namespace/<action_type>');
$store.commit('namespace/<mutation_type>');
```

Currently, vuex-simple modules don't have access to the store instance in their `this` context. If you need your vuex store in your module, you would have to pass it to the constructor when you instantiate your module.

Hope that answered at least a few of your questions.

**Comment by ziazon** [comment]
hmm ok, I'll work with this and see if there are any patterns I like.  Thanks!
