### ISSUE TITLE
Warning in Nuxt about classic mode

### ISSUE THREAD

**Issue by v-kyle** [sascha245/vuex-simple#34]
-  **I'm submitting a**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository
[X] question about how to use this project

-  **Summary**
 When I use Vuex-simple with Nuxt 2 its working good, but I have a warning in console: 
 **Classic mode for store/ is deprecated and will be removed in Nuxt 3.**
Can store be implemented not in classic mode with vuex-simple?

*  **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
 Code, which I use in project with warning:

```
import Vue from 'vue';
import Vuex from 'vuex';
import { createVuexStore } from 'vuex-simple';
import RootStore from './modules/index';

Vue.use(Vuex);
const instance = new RootStore();

const store = createVuexStore(instance, {
  strict: false,
  modules: {},
  plugins: [],
});

export default () => store;
```

**Comment by sascha245** [comment]
Hello @v-kyle,

Today, vuex-simple needs a store instance to work. As such, it doesn't has inbuilt support for Nuxt without classic mode.

This doesn't mean there is no solution at all.
A way to work around this problem is to let nuxt initialize your store and register your current store as a dynamic module afterwards in a nuxt plugin:

```ts
// store/index.ts
// Create an index to tell Nuxt to install Vuex
export const state = {}

// plugins/init.ts
// You can still register a vuex-simple module with a native vuex store
export default ({ store }) => {
  registerModule(store, ['root'], new RootStore());  
}

// Usage 
const rootStore = useModule<RootStore>($store, ['root'])

// You can also create a small helper to access your store more easily
export const useRootStore = (store) => useModule<RootStore>($store, ['root'])
```

I haven't tested this solution, so please tell me if you run into any issues.

Best regards,

**Comment by v-kyle** [comment]
Thank you @sascha245, I tested this solution. I use `const rootStore = useModule<RootStore>($store, ['root'])`, and add plugin and now all wroking good and I haven't warning in console.

But I did not understand about helper function from your answer - where I shoud use it? Now I use `rootStore = useModule ....` in every component  which need state from store.

Also one more problem - `useModule` now can return undefined, and has warning from TS. Thats not very comfortable, example: 

```
Object is possibly 'undefined'.
         someComputed(): string {
           const store = useModule<RootStore>(this.$store, ['root']);
           return store.someSubModule.someProp;
                     ^^^^^
         },
     },

```

Can you advise me something about this (I now that i can use '!' for ts to tell that it is not undefiend) and tell me more about the helper function?

Nevertheless, many thanks for your help, I really like Vuex-simple and like to use it in my projects!!!

**Comment by sascha245** [comment]
Hello,

What I meant by helper function, is that rather than writting `useModule<RootStore>(this.$store, ['root'])` each time, you can write yourself a small utility function like the following:

```ts
// your-utils.ts
export function useRootStore(store: Store<any>): RootStore {
  const instance = useModule<RootStore>($store, ['root'])
  if (!instance) {
    throw new Error('Could not get RootStore module from Vuex store. Please check if the module has been registered correctly.')
  }
  return instance
}
```

Now, instead of using:
```ts
  ...
  someComputed(): string {
    const store = useModule<RootStore>(this.$store, ['root']);
    return store.someSubModule.someProp; // Typescript tells you "store" may be undefined
  },
   ...
```
you can write: 
```ts
  ...
  someComputed(): string {
    const store = useRootStore(this.$store);
    return store.someSubModule.someProp; // No problem anymore
  },
  ...
```

To make store access easier, you could also create another computed returning the store instance:
```ts
  ...
  rootStore(): RootStore {
    return useRootStore(this.$store)
  },
  someComputed(): string {
    return this.rootStore.someSubModule.someProp;
  },
  ...
```
This avoids having to get the store over and over again in your computed / methods.

Hope I answered your questions.

Best regards,

**Comment by v-kyle** [comment]
Hello, 
Thank you for your help, everything works fine now! Vuex-simple works great with Nuxt.
