### ISSUE TITLE
Instance value is set too late.

### ISSUE THREAD

**Issue by mrcrowl** [sascha245/vuex-simple#5]
A recent commit 810b719 modified metadata.ts so that this line:
`Vue.set(instance, propertyName, instance[propertyName]);`
Now appears _after_ the property is replaced with a getter/setter.  

This causes all initial values in the store to be undefined.

See:
https://github.com/sascha245/vuex-simple/blob/e2716417c81cd25322cdc85fb5f9c0f97cf9d833/src/metadata.ts#L72

**Comment by sascha245** [comment]
Oh, my bad! Will fix it as soon as possible.
Strange that my tests passed fine, looks like I will have to review those too.

**Comment by mrcrowl** [comment]
Good work, btw.  I like the track that you're on with this package.

**Comment by sascha245** [comment]
Thanks ^^ Though there are still quite a lot of improvements to be done here and there.

**Comment by sascha245** [comment]
Normally this issue should now be fixed in commit https://github.com/sascha245/vuex-simple/commit/d560982d5556678be2007922230319cdfd816c37 or 1.0.2
