### ISSUE TITLE
@Inject decorator doesn't seem to work 

### ISSUE THREAD

**Issue by mrcrowl** [sascha245/vuex-simple#6]
The `@Inject` decorator doesn't seem to work (at least not on a component, which is where I'm testing it).  

Just a stab in the dark, but I wonder if this is possibly related to replacing your custom decorator with typedi's decorator in PR https://github.com/sascha245/vuex-simple/pull/4?  

```typescript
/// SimpleModule.ts

import { Mutation, Module, Getter, State, getStoreBuilder } from 'vuex-simple';

@Module('simple')
export default class SimpleModule
{
    @State() surname = "Baggins";

    @Getter()
    public get formalName()
    {
        return `Mr. ${this.surname}`
    }

    @Mutation()
    public changeName(newName: string)
    {
        this.surname = newName;
    }
}

/// RootComponent.ts
import { Inject } from "typedi";
import Component from "vue-class-component";
import Vue from "vue";
import SimpleModule from "./store/simple/SimpleModule";

@Component({
    template: `
<div style='background: aliceblue; width: 80%; min-height: 100px'>
    {{ formalName }}
</div>
`})
export default class RootComponent extends Vue
{
    /// THIS PROPERTY IS "undefined"
    @Inject()
    simpleModule: SimpleModule

    get formalName() {
        return this.simpleModule.formalName
    }
}
```

**Comment by sascha245** [comment]
Sorry for being late, was having my lunch.
Did you eventually forget the "Vue.use(VuexSimple)"? It is necessary as it installs a Vue mixin that handles the injection of your modules / services in Vue components.

**Comment by mrcrowl** [comment]
[simple.zip](https://github.com/sascha245/vuex-simple/files/2464581/simple.zip)

Here's a quick example I threw together (See RootComponent.ts particularly).

For now, I've had to put a constructor in that injects `simpleModule` manually.  You can uncomment the `@Inject()` line and remove the constructor to see the problem I was getting.

To run:
```
npm i
npm run dev
```

**Comment by sascha245** [comment]
Ok thanks, I will give you a response as soon as I found out something

**Comment by mrcrowl** [comment]
Thx. All good - no great hurry from me.

Just saw you'd been picked up by the vue newsletter, and realised you'd be
getting a bit of attention.

**Comment by sascha245** [comment]
Reverted back for now, so we will have to do with the custom Inject provided by vuex-simple.
At least with this Inject should now be usable again until I find a good way to make typedi's Inject work.
