### ISSUE TITLE
Is there a way to split the module into files?

### ISSUE THREAD

**Issue by jmotes** [sascha245/vuex-simple#9]
-  **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[X ] question about how to use this project

-  **Summary**
I have a rather large module that I'm currently splitting into separate classes - state, mutations, getters, and actions - and then bringing them together as a Vuex `Module` object for readability purposes. Do you have any recommendations for doing the same with vuex-simple? I was reading up on Typescript partial types, but not 100% sure if that's the best route.

Thanks!

*  **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by sascha245** [comment]
Hi @jmotes ,

As I don't know exactly what you have in the module I will just propose different solutions you could use for now:
1. Do all the heavy lifting (API calls and such ) in different files or services
2. Split up your module into smaller modules ( if it's possible )
3. I could eventually introduce inheritance handling on the fly in 1.2.0, as it shouldn't be too difficult to add. That way you could split up your code in the following way:
```ts
class CounterState {
  @State()
  public counter: number = 10;
}

class CounterGetters extends CounterState {
  @Getter()
  public get counterPlusHundred() {
    return this.counter + 100;
  }
}

class CounterMutations extends CounterGetters {
  @Mutation()
  public increment() {
    this.counter++;
  }
}

class CounterActions extends CounterMutations {
  public async incrementAsync() {
    await new Promise(r => setTimeout(r, 500));
    this.increment();
  }
}

@Module('counter')
class CounterModule extends CounterActions {}

```

What do you think about the last solution? Though it isn't perfect and probably also isn't the best way to handle this problem, it should enable us to split the module into separate parts.

Don't hesitate to tell me if you have other better ideas!

**Comment by sascha245** [comment]
Hi @jmotes,

1.2.0 is now out with #10 and includes as said inheritance in the same way as presented above.
Hope it solves your problems.

Sascha

**Comment by jmotes** [comment]
Thanks @sascha245!
